version: '3.5'

services:
  app:
    depends_on:
      - db
    image: ghcr.io/alexeypetrochenko/notification_service_fastapi:v1.0.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    command: >
      sh -c "alembic upgrade head && uvicorn app.server:create_app --host 0.0.0.0 --factory"

  worker:
    depends_on:
      - db
      - app
    image: ghcr.io/alexeypetrochenko/notification_service_fastapi:v1.0.1
    env_file:
      - .env
    networks:
      - app-network
    command: >
      sh -c "python3 -m app.workers.campaign_worker"
  
  db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network: