version: '3.5'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "alembic upgrade head && uvicorn app.server:create_app --host 0.0.0.0 --factory"
  
  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - app
    networks:
      - app-network
    command: >
      sh -c "python3 -m app.workers.campaign_worker"

  db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - app-network

  test_db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
    ports:
      - "5433:5432"

networks:
  app-network:
