"""create recipient

Revision ID: f484b86ad2fa
Revises: 7f29a816be1a
Create Date: 2024-10-14 19:57:06.941298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f484b86ad2fa'
down_revision: Union[str, None] = '7f29a816be1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('campaign')
    op.execute('DROP TYPE IF EXISTS statuscampaign;')
    
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'FAILED', 'DONE', name='statuscampaign'), nullable=False),
    sa.Column('launch_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipients',
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('recipient_id'),
    sa.UniqueConstraint('contact_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'RUNNING', 'FAILED', 'DONE', name='statuscampaign'), autoincrement=False, nullable=False),
    sa.Column('launch_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name='campaign_pkey'),
    sa.UniqueConstraint('name', name='campaign_name_key')
    )
    op.drop_table('recipients')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
