name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Install dependencies
        run: uv sync --group lint --group tests --frozen --no-cache
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Run tests
        run: python3 -m pytest .